### ISSUE TITLE
Missing controller includes

### ISSUE THREAD

**Issue by brandon099** [jichuntao/online_compiler#1]
The following controllers that are referenced in the app.js are missing from the repository:

./controller/layout
./controller/compile

Were these excluded intentionally, or can they be added to the repository to allow running the nodeJS app?

Thank you!

**Comment by TheLevenCreations** [comment]
I just found these missing files are deleted in previous commits. Just check them out and add :)

**Comment by thatarchguy** [comment]
Wondering this myself. Even with:
```
git checkout 94e84108b4232e4f3418710a65e6ca046884463e -- controller/
```
It's still missing controller/layout
```
module.js:472
    throw err;
    ^

Error: Cannot find module './controller/layout'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/dev/_cloned/online_compiler/app.js:9:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by Carlovan** [comment]
The problem is that the `controller` folder is specified inside `.gitignore`.  
You should definitely fix `.gitignore` and repush the `controller` folder because it's 2 years old.
